# Generated by Django 5.0.6 on 2024-06-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HolidayHousing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('F', 'flat'), ('H', 'house'), ('S', 'special location')], max_length=1)),
                ('costs', models.CharField(choices=[('C', 'cheap'), ('A', 'affordable'), ('E', 'expensive'), ('L', 'luxury')], max_length=1)),
                ('location', models.CharField(choices=[('M', 'metropolis'), ('V', 'village'), ('N', 'nature'), ('C', 'city')], max_length=1)),
                ('title', models.CharField(max_length=50)),
                ('rooms', models.IntegerField()),
                ('specials', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Holiday Housing',
                'verbose_name_plural': 'Holiday Housings',
                'ordering': ['costs', 'type', 'location'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_or_down', models.CharField(choices=[('U', 'up'), ('D', 'down')], max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
