# Generated by Django 5.0.6 on 2024-06-13 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HolidayHousings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='myuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holidayhousing',
            name='myuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_housing_created_by', related_query_name='holiday_housing_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='holiday_housing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HolidayHousings.holidayhousing'),
        ),
        migrations.AddField(
            model_name='vote',
            name='holiday_housing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HolidayHousings.holidayhousing'),
        ),
        migrations.AddField(
            model_name='vote',
            name='myuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
