# Generated by Django 4.2 on 2024-07-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HolidayHousings', '0004_comment_star_rating_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayhousing',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='holiday_housing_pdfs/'),
        ),
        migrations.AlterField(
            model_name='holidayhousing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='holiday_housing_images/'),
        ),
    ]
