# Generated by Django 4.2 on 2024-07-13 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HolidayHousings', '0007_alter_comment_options_alter_comment_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['timestamp'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
