# Generated by Django 4.2 on 2024-07-14 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HolidayHousings', '0010_comment_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
    ]
