# Generated by Django 4.2 on 2024-07-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HolidayHousings', '0011_remove_comment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
